const H=require('../helpers/env.cjs');
const puppeteer=require('puppeteer-core');const fs=require('fs');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const html=H.indexHtml();
const hooked=H.hookedHtml();
const SHOT=H.ARTIFACTS+'/';
(async()=>{
  await H.ensureServer();
  const browser=await puppeteer.launch({executablePath:H.CHROME,headless:true});
  const errs=[];
  const p=await browser.newPage();await p.setViewport({width:1280,height:900});
  p.on('pageerror',e=>errs.push('pageerror: '+e.message));
  // Supabase is blocked on purpose in this test, so its failed requests are expected
  p.on('console',m=>{const at=(m.location()&&m.location().url)||'';if(m.type()==='error'&&!at.includes('supabase.co'))errs.push('console: '+m.text()+' @ '+at)});
  await p.setRequestInterception(true);
  p.on('request',r=>{const u=r.url();if(u==='http://localhost:3210/')r.respond({status:200,contentType:'text/html',body:hooked});else if(u.includes('supabase.co'))r.abort();else r.continue()});
  await p.goto('http://localhost:3210/',{waitUntil:'domcontentloaded'});await sleep(800);
  const run=(b)=>p.evaluate(b=>__ev('(async()=>{'+b+'})()'),b);
  const step=async(name,code)=>{try{const r=await run(code);console.log('PASS',name,r!==undefined?JSON.stringify(r).slice(0,160):'')}catch(e){errs.push(name+': '+e.message);console.log('FAIL',name,e.message.slice(0,200))}};
  await step('local mode',`hideGate();hideSetup();authUser=null;sbStatus="disconnected";renderAll();`);
  await step('load examples',`loadExamples();return {products:products().length,variants:products().reduce((a,p)=>a+p.variants.length,0),moves:Object.keys(moves).length}`);
  await step('sell tab render',`setTab("stock");setTab("sell");return $$("#grid .tile").length`);
  await p.screenshot({path:SHOT+'v_sell.png'});
  await step('open picker',`openPicker("p1");return $$("#sheetHost .vc").length`);
  await p.screenshot({path:SHOT+'v_picker.png'});
  await step('pick qty',`const p=prod("p1");const v=p.variants.find(x=>x.o[0]==="Black"&&x.o[1]==="L"),w=p.variants.find(x=>x.o[0]==="White"&&x.o[1]==="M");setPickQty(v.id,2);setPickQty(w.id,3);addPicked();return cart.map(c=>[c.c,c.s,c.q])`);
  await step('customer add',`customers["c1"]={id:"c1",name:"Riya",phone:"9876543210",email:"",t:Date.now()};cartCust={id:"c1",name:"Riya",phone:"9876543210"};renderAll();return cartCust.name`);
  await step('checkout',`await checkout("cash");return {sales:D().sales.length,paid:!!$("#sheetHost [data-paid]")}`);
  await p.screenshot({path:SHOT+'v_paid.png'});
  await step('stock after sale',`const p=prod("p1");const v=p.variants.find(x=>x.o[0]==="Black"&&x.o[1]==="L");return stockOf(v.id)`);
  await step('receipt html',`const s=D().sales[0];return receiptHTML(s,"80mm").length+" "+receiptText(s).split("\\n").length`);
  await step('receipt png',`const b=await receiptPNG(D().sales[0]);return b&&b.size`);
  await step('bill view',`closeSheets();openBillView(D().sales[0].id);return !!$("#modalHost .billview")`);
  await p.screenshot({path:SHOT+'v_billview.png'});
  await step('return sheet',`openReturn(D().sales[0].id);retState.q[0]=1;renderReturnSheet();return !!$("#sheetHost .retsheet")`);
  await p.screenshot({path:SHOT+'v_return.png'});
  await step('save return',`saveReturn();return Object.keys(returnsMap).length`);
  await step('stock after return',`const p=prod("p1");const v=p.variants.find(x=>x.o[0]==="Black"&&x.o[1]==="L");return stockOf(v.id)`);
  await step('exchange',`openReturn(D().sales[0].id);retState.mode="exchange";retState.q[1]=1;const p=prod("p1");const w=p.variants.find(x=>x.o[0]==="Navy"&&x.o[1]==="XL");addToLines(retState.newItems,w.id,1);renderReturnSheet();saveReturn();return {rets:Object.keys(returnsMap).length,sales:D().sales.length}`);
  await step('stock tab',`closeSheets();setTab("stock");return $$("#stockBody .spc").length`);
  await p.screenshot({path:SHOT+'v_stock.png',fullPage:true});
  await step('stock in',`openStockOp("in","p1");const v=prod("p1").variants[0];stockOp.val[v.id]="5";renderStockOp();saveStockOp();return stockOf(v.id)`);
  await step('adjust',`openStockOp("adjust","p1");const v=prod("p1").variants[0];stockOp.val[v.id]=String(stockOf(v.id)-1);saveStockOp();return stockOf(v.id)`);
  await step('reports',`setTab("report");prefs.period="today";renderReport();return $$("#repBody .card").length`);
  await p.screenshot({path:SHOT+'v_report.png',fullPage:true});
  await step('products',`setTab("products");return $$("#prodBody .pcard").length`);
  await p.screenshot({path:SHOT+'v_products.png'});
  await step('editor new',`openEditor(null);editor.name="Test Tee";editor.price="499";edToggleOptions(true);edAddOption("Colour");edAddValues(0,["Black","White","Navy","Red"]);edAddOption("Size");edAddValues(1,["S","M","L","XL","XXL"]);return edCombos().length`);
  await p.screenshot({path:SHOT+'v_editor.png'});
  await step('editor save',`edCombos().forEach((x,i)=>x.cell.stock=String(i+1));edGenSkus();saveEditor();const p=products().find(x=>x.name==="Test Tee");return {v:p.variants.length,stock:p.variants.map(v=>stockOf(v.id)).reduce((a,b)=>a+b,0),sku:p.variants[0].sku}`);
  await step('settings',`authUser={id:"u1",email:"a@b.co",user_metadata:{},identities:[{provider:"email"}]};profile={full_name:"A",shop_name:"Shop"};openSettings();return !!$("#billingForm")`);
  await p.screenshot({path:SHOT+'v_settings.png'});
  await step('backup inspect',`const data={app:"hangtag",version:3,catalog,days:Object.assign({},localDays),moves,returns:returnsMap,customers,images:imgs};return inspectBackup(data).summary`);
  await step('csv',`prefs.period="today";const R=periodRange();return periodData(R.from,R.to).all.length`);
  await step('group suggestion',`catalog={version:1,products:[{id:"q1",name:"Tee – Black",price:599,color:"#000000",sizes:[{s:"M",stock:5}]},{id:"q2",name:"Tee – White",price:599,color:"#ffffff",sizes:[{s:"M",stock:4}]}]};applyCatalogMigration();return colorGroups().map(g=>g.base+":"+g.items.length)`);
  console.log('\nERRORS:',errs.length?errs:'none');
  await browser.close();
  process.exit(errs.length?1:0);
})();
