// Test-only hook. When a test sets window.__HANGTAG_TEST__ before the app loads, window.__ev(src)
// evaluates src with the app's state and every module export in scope (as the single-file app allowed).
// It is never installed in normal use.
import { APP_ENV } from '../shared/config/app-config.js';
import { store, STATE_KEYS } from '../shared/state/store.js';
// BUILD:MODULES:START (generated by scripts/build.mjs: every module except main.js and this file)
import * as m0 from './container.js';
import * as m1 from './events/dom-events.js';
import * as m2 from './events/keyboard.js';
import * as m3 from './events/window-events.js';
import * as m4 from './navigation.js';
import * as m5 from './pwa.js';
import * as m6 from './state-init.js';
import * as m7 from '../domain/catalog/barcode.js';
import * as m8 from '../domain/catalog/catalog-migration.js';
import * as m9 from '../domain/catalog/options.js';
import * as m10 from '../domain/catalog/product-validation.js';
import * as m11 from '../domain/catalog/sizes.js';
import * as m12 from '../domain/catalog/variants.js';
import * as m13 from '../domain/inventory/bill-import.js';
import * as m14 from '../domain/inventory/stock-levels.js';
import * as m15 from '../domain/inventory/stock-operation.js';
import * as m16 from '../domain/sales/bill-totals.js';
import * as m17 from '../domain/sales/cart-rules.js';
import * as m18 from '../domain/sales/sale.js';
import * as m19 from '../domain/sales/scan-rules.js';
import * as m20 from '../domain/shop/profile-validation.js';
import * as m21 from '../domain/shop/profile.js';
import * as m22 from '../domain/shop/settings-validation.js';
import * as m23 from '../domain/shop/settings.js';
import * as m24 from '../features/auth/components/auth-gate.js';
import * as m25 from '../features/auth/components/sign-in-form.js';
import * as m26 from '../features/auth/config.js';
import * as m27 from '../features/auth/services/account-data.js';
import * as m28 from '../features/auth/services/auth-errors.js';
import * as m29 from '../features/auth/services/auth-settings.js';
import * as m30 from '../features/auth/services/session.js';
import * as m31 from '../features/backup/components/restore-dialog.js';
import * as m32 from '../features/backup/services/backup-file.js';
import * as m33 from '../features/customers/components/customer-picker.js';
import * as m34 from '../features/customers/services/customer-stats.js';
import * as m35 from '../features/inventory/components/bill-import.js';
import * as m36 from '../features/inventory/components/product-chooser.js';
import * as m37 from '../features/inventory/components/stock-operation.js';
import * as m38 from '../features/inventory/pages/stock-page.js';
import * as m39 from '../features/inventory/repositories/stock-repository.js';
import * as m40 from '../features/inventory/services/ledger.js';
import * as m41 from '../features/inventory/services/stock-levels.js';
import * as m42 from '../features/inventory/services/stock.js';
import * as m43 from '../features/inventory/use-cases/import-supplier-bill.js';
import * as m44 from '../features/inventory/use-cases/record-stock-operation.js';
import * as m45 from '../features/products/components/colour-groups.js';
import * as m46 from '../features/products/components/product-actions.js';
import * as m47 from '../features/products/components/product-editor.js';
import * as m48 from '../features/products/components/stickers.js';
import * as m49 from '../features/products/components/thumb.js';
import * as m50 from '../features/products/pages/products-page.js';
import * as m51 from '../features/products/repositories/product-repository.js';
import * as m52 from '../features/products/services/catalog.js';
import * as m53 from '../features/products/services/examples.js';
import * as m54 from '../features/products/services/matrix.js';
import * as m55 from '../features/products/use-cases/product-lifecycle.js';
import * as m56 from '../features/products/use-cases/product-photo.js';
import * as m57 from '../features/products/use-cases/save-product.js';
import * as m58 from '../features/receipts/components/bill-view.js';
import * as m59 from '../features/receipts/components/receipt-view.js';
import * as m60 from '../features/receipts/services/receipt-model.js';
import * as m61 from '../features/receipts/services/receipt-output.js';
import * as m62 from '../features/reports/pages/report-page.js';
import * as m63 from '../features/reports/services/csv-export.js';
import * as m64 from '../features/reports/services/report-data.js';
import * as m65 from '../features/returns/components/return-sheet.js';
import * as m66 from '../features/returns/services/return-rules.js';
import * as m67 from '../features/sales/components/bill-panel.js';
import * as m68 from '../features/sales/components/camera-scan.js';
import * as m69 from '../features/sales/components/payment-done.js';
import * as m70 from '../features/sales/components/variant-picker.js';
import * as m71 from '../features/sales/pages/sell-page.js';
import * as m72 from '../features/sales/services/cart.js';
import * as m73 from '../features/sales/services/sales-log.js';
import * as m74 from '../features/sales/services/search.js';
import * as m75 from '../features/sales/services/totals.js';
import * as m76 from '../features/sales/use-cases/checkout.js';
import * as m77 from '../features/sales/use-cases/scan-to-cart.js';
import * as m78 from '../features/shop/components/account-events.js';
import * as m79 from '../features/shop/components/account-menu.js';
import * as m80 from '../features/shop/components/billing-settings.js';
import * as m81 from '../features/shop/components/profile-form.js';
import * as m82 from '../features/shop/components/settings-modal.js';
import * as m83 from '../features/shop/components/setup-gate.js';
import * as m84 from '../features/shop/services/profile-service.js';
import * as m85 from '../features/shop/use-cases/save-billing-settings.js';
import * as m86 from '../features/shop/use-cases/save-shop-profile.js';
import * as m87 from '../features/sync/components/sync-status.js';
import * as m88 from '../features/sync/services/connection.js';
import * as m89 from '../features/sync/services/outbox.js';
import * as m90 from '../features/sync/services/pull.js';
import * as m91 from '../features/sync/services/remote-events.js';
import * as m92 from '../infrastructure/browser/files.js';
import * as m93 from '../infrastructure/codes/barcode-svg.js';
import * as m94 from '../infrastructure/codes/png.js';
import * as m95 from '../infrastructure/codes/qr-svg.js';
import * as m96 from '../infrastructure/codes/vendor/qrcode-generator.js';
import * as m97 from '../infrastructure/extraction/bill-extractor.js';
import * as m98 from '../infrastructure/repositories/local-first-product-repository.js';
import * as m99 from '../infrastructure/repositories/local-first-stock-import.js';
import * as m100 from '../infrastructure/repositories/local-first-stock-repository.js';
import * as m101 from '../infrastructure/scanner/camera-scanner.js';
import * as m102 from '../infrastructure/scanner/vendor/zxing-decode.js';
import * as m103 from '../infrastructure/storage/local-storage.js';
import * as m104 from '../infrastructure/supabase/client.js';
import * as m105 from '../infrastructure/supabase/cloud-gateway.js';
import * as m106 from '../infrastructure/supabase/errors.js';
import * as m107 from '../infrastructure/supabase/mappers.js';
import * as m108 from '../infrastructure/supabase/query.js';
import * as m109 from '../shared/components/charts.js';
import * as m110 from '../shared/components/gate.js';
import * as m111 from '../shared/components/kpi.js';
import * as m112 from '../shared/components/modal.js';
import * as m113 from '../shared/components/toast.js';
import * as m114 from '../shared/components/tooltip.js';
import * as m115 from '../shared/config/app-config.js';
import * as m116 from '../shared/constants/icons.js';
import * as m117 from '../shared/di/ports.js';
import * as m118 from '../shared/di/services.js';
import * as m119 from '../shared/dom.js';
import * as m120 from '../shared/errors/app-error.js';
import * as m121 from '../shared/formatting/dates.js';
import * as m122 from '../shared/formatting/money.js';
import * as m123 from '../shared/logging/logger.js';
import * as m124 from '../shared/state/persistence.js';
import * as m125 from '../shared/ui/render.js';
import * as m126 from '../shared/ui/session-actions.js';
import * as m127 from '../shared/utils/colors.js';
import * as m128 from '../shared/utils/ids.js';
import * as m129 from '../shared/utils/objects.js';
import * as m130 from '../shared/utils/text.js';
import * as m131 from '../shared/validation/email.js';
import * as m132 from '../shared/validation/gstin.js';
import * as m133 from '../shared/validation/phone.js';

const MODULE_NAMESPACES = [m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15, m16, m17, m18, m19, m20, m21, m22, m23, m24, m25, m26, m27, m28, m29, m30, m31, m32, m33, m34, m35, m36, m37, m38, m39, m40, m41, m42, m43, m44, m45, m46, m47, m48, m49, m50, m51, m52, m53, m54, m55, m56, m57, m58, m59, m60, m61, m62, m63, m64, m65, m66, m67, m68, m69, m70, m71, m72, m73, m74, m75, m76, m77, m78, m79, m80, m81, m82, m83, m84, m85, m86, m87, m88, m89, m90, m91, m92, m93, m94, m95, m96, m97, m98, m99, m100, m101, m102, m103, m104, m105, m106, m107, m108, m109, m110, m111, m112, m113, m114, m115, m116, m117, m118, m119, m120, m121, m122, m123, m124, m125, m126, m127, m128, m129, m130, m131, m132, m133];
// BUILD:MODULES:END

export function installTestHook(){
  if(APP_ENV !== "test") return;   // set by window.__HANGTAG_TEST__ (shared/config/app-config.js)
  const byName = new Map();
  MODULE_NAMESPACES.forEach(ns => Object.keys(ns).forEach(k => byName.set(k, ns)));
  const state = new Set(STATE_KEYS);
  const scope = new Proxy(Object.create(null), {
    has: (_, k) => typeof k === "string" && (state.has(k) || byName.has(k)),
    get: (_, k) => k === Symbol.unscopables ? undefined : state.has(k) ? store[k] : byName.get(k)[k],
    set: (_, k, v) => { if(state.has(k)){ store[k] = v; return true; } throw new TypeError(String(k) + " is a module export and can't be replaced from a test"); }
  });
  // A non-strict Function so the evaluated code can use `with` scope lookups.
  const run = new Function("scope", "src", "with (scope) { return eval(src); }");
  window.__ev = src => run(scope, src);
}
