// Build checks for Hangtag. The app runs as native ES modules straight from the repository (GitHub Pages),
// so "build" means: keep the offline file list current and prove the app is consistent.
//   node scripts/build.mjs          update sw.js (file list + cache version), check architecture, bundle-check, lint
//   node scripts/build.mjs --check  same checks, but fail instead of writing when sw.js is out of date (CI/tests)
//   The deployable site is the repository root (GitHub Pages). A normal build also copies exactly those files
//   (the offline file list + sw.js) to dist/site for hosts that serve a build folder (Vercel: vercel.json).
import { createHash } from 'node:crypto';
import { cpSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import esbuild from 'esbuild';
import { ESLint } from 'eslint';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const walk = (d) => readdirSync(d).flatMap((f) => { const p = path.join(d, f); return statSync(p).isDirectory() ? walk(p) : [p]; });
const toUrl = (p) => './' + path.relative(ROOT, p).split(path.sep).join('/');

const appFiles = walk(path.join(ROOT, 'src')).filter((p) => /\.(js|css)$/.test(p)).sort();
let failed = false;

// 1. The test hook reaches every module (tests/test-api.json names can live in any of them)
const hookPath = path.join(ROOT, 'src/app/test-hook.js');
const hook = readFileSync(hookPath, 'utf8').replace(/\r\n/g, '\n');
const jsFiles = appFiles.filter((p) => p.endsWith('.js'))
  .map((p) => path.relative(path.join(ROOT, 'src/app'), p).split(path.sep).join('/'))
  .map((r) => (r.startsWith('.') ? r : './' + r))
  .filter((r) => r !== './main.js' && r !== './test-hook.js' && r !== '../shared/state/store.js');
const HS = '// BUILD:MODULES:START', HE = '// BUILD:MODULES:END';
const hookBlock = `${HS} (generated by scripts/build.mjs: every module except main.js and this file)
${jsFiles.map((r, i) => `import * as m${i} from '${r}';`).join('\n')}

const MODULE_NAMESPACES = [${jsFiles.map((_, i) => `m${i}`).join(', ')}];
${HE}`;
const newHook = hook.replace(new RegExp(`${HS}[\\s\\S]*?${HE}`), hookBlock);
if (newHook !== hook) {
  if (CHECK) { console.error('src/app/test-hook.js module list is out of date: run "npm run build"'); failed = true; }
  else { writeFileSync(hookPath, newHook); console.log(`test hook updated: ${jsFiles.length} modules`); }
}

// 2. Files the service worker saves (after step 1, so the cache version covers the final files) for offline use: the app shell plus every module and stylesheet.
const STATIC = ['index.html', 'config.js', 'manifest.webmanifest', 'icon.svg', 'icon-192.png', 'icon-512.png', 'apple-touch-icon.png'];
const shellFiles = [...STATIC.map((f) => path.join(ROOT, f)), ...appFiles];
const hash = createHash('sha256');
for (const f of shellFiles) { hash.update(toUrl(f)); hash.update(readFileSync(f)); }
const version = hash.digest('hex').slice(0, 10);
const SHELL = ['./', ...shellFiles.map(toUrl)];

const swPath = path.join(ROOT, 'sw.js');
const sw = readFileSync(swPath, 'utf8').replace(/\r\n/g, '\n');
const START = '// BUILD:START', END = '// BUILD:END';
const block = `${START} (generated by scripts/build.mjs: run "npm run build" after changing app files)
const CACHE = "hangtag-${version}";
const SHELL = ${JSON.stringify(SHELL, null, 2)};
${END}`;
if (!sw.includes(START)) throw new Error('sw.js has no BUILD:START/BUILD:END block');
const newSw = sw.replace(new RegExp(`${START}[\\s\\S]*?${END}`), block);
if (newSw !== sw) {
  if (CHECK) { console.error('sw.js is out of date: run "npm run build"'); failed = true; }
  else { writeFileSync(swPath, newSw); console.log(`sw.js updated: ${SHELL.length} files, cache hangtag-${version}`); }
} else console.log(`sw.js up to date: ${SHELL.length} files, cache hangtag-${version}`);

// 3. Architecture rules (dependency direction, no Supabase outside infrastructure, pure domain)
const arch = spawnSync(process.execPath, [path.join(ROOT, 'scripts', 'check-architecture.mjs')], { encoding: 'utf8' });
process.stdout.write(arch.stdout); process.stderr.write(arch.stderr);
if (arch.status !== 0) failed = true;

// 4. Bundle check: every import resolves and every module parses (output is not deployed)
try {
  const r = await esbuild.build({ entryPoints: [path.join(ROOT, 'src/app/main.js')], bundle: true, format: 'esm',
    outfile: path.join(ROOT, 'dist/app.bundle.js'), logLevel: 'error', metafile: true });
  console.log(`bundle ok: ${Object.keys(r.metafile.inputs).length} modules`);
} catch (e) { console.error('bundle failed'); failed = true; }

// 5. Lint (eslint.config.js): no undefined names (a missing import) and no unused variables
const eslint = new ESLint({ cwd: ROOT });
const lint = await eslint.lintFiles(['src']);
const lintErrors = lint.reduce((n, r) => n + r.errorCount, 0), lintWarnings = lint.reduce((n, r) => n + r.warningCount, 0);
if (lintErrors || lintWarnings) {
  process.stderr.write(await (await eslint.loadFormatter('stylish')).format(lint));
  if (lintErrors) failed = true;
}
console.log(`lint ${lintErrors ? 'failed' : 'ok'}: ${lint.length} files, ${lintErrors} errors, ${lintWarnings} warnings`);

// 6. Deployable copy for Vercel (dist/site): the app shell and every module/stylesheet the service worker lists, plus
//    sw.js and the maskable icon the manifest names. Nothing else (no tests, scripts, supabase/ or node_modules).
if (!CHECK && !failed) {
  const SITE = path.join(ROOT, 'dist', 'site');
  rmSync(SITE, { recursive: true, force: true });
  for (const f of [...shellFiles, path.join(ROOT, 'sw.js'), path.join(ROOT, 'icon-maskable-512.png')]) {
    const to = path.join(SITE, path.relative(ROOT, f));
    mkdirSync(path.dirname(to), { recursive: true });
    cpSync(f, to);
  }
  console.log(`site ok: dist/site (${shellFiles.length + 2} files)`);
}

process.exit(failed ? 1 : 0);
